spring.application.name=backend

spring.security.user.name=arpan

spring.security.user.password=arpan


spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=${USR_NAME}
spring.datasource.password=${PASS}
